# Regenerates app/services/icons.rb from a checkout of Weather Iconic.
#
#   git clone https://github.com/konradmichalik/weather-iconic /tmp/weather-iconic
#   ruby script/generate_weather_icons.rb /tmp/weather-iconic
#
# Only the black-and-white ("single-color") source SVGs are used; the
# multicolor styling in that set is applied via CSS, which an e-ink
# dashboard has no colour to spend on.

src = File.join(ARGV.fetch(0), "src", "icons")
abort "no icons at #{src}" unless Dir.exist?(src)

# Glyph name => the Weather Iconic source file (without extension).
GLYPHS = {
  "sun"            => "sun",
  "sun_cloud"      => "sun-cloud",
  "clouds"         => "clouds",
  "cloud_fog"      => "cloud-fog",
  "cloud_rain"     => "cloud-rain",
  "cloud_rain_alt" => "cloud-rain-alt",
  "cloud_sleet"    => "cloud-sleet",
  "cloud_snow"     => "cloud-snow",
  "cloud_snow_alt" => "cloud-snow-alt",
  "lightning"      => "lightning",
  "na"             => "na"
}.freeze

def inner(path)
  raw = File.read(path).sub(/<\?xml.*?\?>/m, "").sub(/<!DOCTYPE.*?>/m, "").strip
  body = raw[%r{<svg\b[^>]*>(.*)</svg>}m, 1].strip
  body.gsub(/>\s+</, "><").gsub(/\s{2,}/, " ").strip
end

rows = GLYPHS.map do |key, file|
  body = inner(File.join(src, "#{file}.svg"))
  raise "brace in #{file}" if body.match?(/[{}]/)

  %(    "#{key}" => %q{#{body}}.freeze)
end

header = <<~RUBY
  # app/services/icons.rb
  #
  # Weather glyphs are the black-and-white ("single-color") variant of
  # Weather Iconic by Konrad Michalik — https://github.com/konradmichalik/weather-iconic
  # Licensed CC BY-SA 3.0 US. Each value is the inner markup of a 32x32
  # viewBox SVG; IconHelper#weather_icon wraps it and paints it with
  # currentColor so it inverts with its card like the rest of the ink.
  #
  # Generated by script/generate_weather_icons.rb — do not hand-edit the paths.
  module Icons
    VIEWBOX = 32

    WEATHER = {
RUBY

footer = <<~RUBY
    }.freeze

    # Open-Meteo reports conditions as WMO weather codes. Ranges collapse
    # intensity levels onto one glyph; "-alt" glyphs carry the heavy end.
    # https://open-meteo.com/en/docs#weather_variable_documentation
    def self.for_wmo(code)
      return "na" if code.nil?

      case code.to_i
      when 0, 1            then "sun"            # clear / mainly clear
      when 2               then "sun_cloud"      # partly cloudy
      when 3               then "clouds"         # overcast
      when 45, 48          then "cloud_fog"      # fog / rime fog
      when 51, 53, 61, 63, 80, 81 then "cloud_rain"      # drizzle, rain, showers
      when 55, 65, 82      then "cloud_rain_alt" # dense drizzle, heavy rain, violent showers
      when 56, 57, 66, 67  then "cloud_sleet"    # freezing drizzle / freezing rain
      when 71, 73, 77, 85  then "cloud_snow"     # snow, snow grains, snow showers
      when 75, 86          then "cloud_snow_alt" # heavy snow / heavy snow showers
      when 95, 96, 99      then "lightning"      # thunderstorm
      else "clouds"
      end
    end

    def self.label_for_wmo(code)
      case code.to_i
      when 0 then "Clear"
      when 1 then "Mostly clear"
      when 2 then "Partly cloudy"
      when 3 then "Overcast"
      when 45, 48 then "Fog"
      when 51..57 then "Drizzle"
      when 61..67 then "Rain"
      when 71..77 then "Snow"
      when 80..82 then "Showers"
      when 85, 86 then "Snow showers"
      when 95..99 then "Thunderstorms"
      else "—"
      end
    end
  end
RUBY

path = File.expand_path("../app/services/icons.rb", __dir__)
File.write(path, header + rows.join(",\n") + "\n" + footer)
puts "wrote #{path}"
