# Regenerates app/services/icons.rb from a checkout of Weather Icons.
#
#   git clone https://github.com/sylturner/weather-icons /tmp/weather-icons
#   ruby script/generate_weather_icons.rb /tmp/weather-icons
#
# The Open-Meteo code => glyph mapping is read from that fork's
# less/mappings/wi-openmeteo.less, and only the glyphs it references
# (plus "na") are pulled from svg/.

root = ARGV.fetch(0)
mapping_path = File.join(root, "less", "mappings", "wi-openmeteo.less")
abort "no Open-Meteo mapping at #{mapping_path}" unless File.exist?(mapping_path)

# .@{wi-css-prefix}-openmeteo-day-0:before { content: @day-sunny ; }
RULE = /-openmeteo-(?:(day|night)-)?(\d+):before\s*\{\s*content:\s*@([a-z0-9-]+)/

mapping = { "neutral" => {}, "day" => {}, "night" => {} }
File.foreach(mapping_path) do |line|
  next unless (m = line.match(RULE))

  mapping[m[1] || "neutral"][m[2].to_i] = m[3]
end
abort "no rules parsed from #{mapping_path}" if mapping.values.any?(&:empty?)

def inner(path)
  raw = File.read(path).sub(/<\?xml.*?\?>/m, "").gsub(/<!--.*?-->/m, "").strip
  body = raw[%r{<svg\b[^>]*>(.*)</svg>}m, 1].strip
  body.gsub(/>\s+</, "><").gsub(/\s+/, " ").strip
end

glyphs = (mapping.values.flat_map(&:values) + [ "na" ]).uniq.sort
rows = glyphs.map do |name|
  body = inner(File.join(root, "svg", "wi-#{name}.svg"))
  raise "paren in #{name}" if body.match?(/[()]/)

  %(    "#{name}" => %q(#{body}).freeze)
end

codes = mapping.map do |variant, table|
  pairs = table.sort.map { |code, name| %(      #{code} => "#{name}") }
  "    #{variant}: {\n#{pairs.join(",\n")}\n    }.freeze"
end

header = <<~RUBY
  # app/services/icons.rb
  #
  # Weather glyphs are Weather Icons by Erik Flowers, from the fork at
  # https://github.com/sylturner/weather-icons that adds an Open-Meteo
  # mapping. Licensed SIL OFL 1.1. Each value is the inner markup of a
  # 30x30 viewBox SVG; IconHelper#weather_icon wraps it and paints it with
  # currentColor so it inverts with its card like the rest of the ink.
  #
  # Generated by script/generate_weather_icons.rb — do not hand-edit.
  module Icons
    VIEWBOX = 30

    WEATHER = {
RUBY

middle = <<-RUBY
  }.freeze

  # Open-Meteo WMO weather code => glyph, per wi-openmeteo.less.
  # https://open-meteo.com/en/docs#weather_variable_documentation
  OPEN_METEO = {
RUBY

footer = <<~RUBY
    }.freeze

    # Fall back to the overcast glyph for any code the mapping doesn't
    # cover. `is_day` is Open-Meteo's 1/0 flag; leave it nil where the API has
    # no such flag to get the time-neutral glyph.
    def self.for_wmo(code, is_day: nil)
      return "na" if code.nil?

      variant = case is_day
      when nil then :neutral
      when 1, true then :day
      else :night
      end

      OPEN_METEO[variant].fetch(code.to_i) { OPEN_METEO[variant].fetch(3) }
    end

    # `short` trims the long names for tight rows like the daily forecast.
    def self.label_for_wmo(code, short: false)
      case code.to_i
      when 0 then "Clear"
      when 1 then "Mostly clear"
      when 2 then "Partly cloudy"
      when 3 then "Overcast"
      when 45, 48 then "Fog"
      when 51..57 then "Drizzle"
      when 61..67 then "Rain"
      when 71..77 then "Snow"
      when 80..82 then "Showers"
      when 85, 86 then "Snow showers"
      when 95..99 then short ? "T-Storms" : "Thunderstorms"
      else "—"
      end
    end
  end
RUBY

path = File.expand_path("../app/services/icons.rb", __dir__)
File.write(path, header + rows.join(",\n") + "\n" + middle + codes.join(",\n") + "\n" + footer)
puts "wrote #{path}"
